### ISSUE TITLE
problem displaying names of concepts

### ISSUE THREAD

**Issue by levilucio** [mbeddr/language_verification#16]
I want to refer to concepts of a language, and for that I am using

ConceptIdRefExpression (jetbrains.mps.lang.smodel.structure)

This works fine, but when I do select a concept and display its name, the name of the concept shows up in red in my editor (without any explanation for the error). I thought this would come from a constraint on the name, but the names have nothing is particular and are proper names of concepts in their languages.

**Comment by saadbinabid1** [comment]
I think this is sorted out in the improved editor when working with enhancements.. you can close this...
