### ISSUE TITLE
textgen for toplevel.py fails

### ISSUE THREAD

**Issue by levilucio** [mbeddr/language_verification#25]
- run textgen on any DSLTrans transformation
- an error appears on toplevel.py
- fix it

**Comment by BentleyJOakes** [comment]
Is there an error with something I wrote? What's the error message?

**Comment by levilucio** [comment]
The error showed up because we changed the name (string) references to the input and output languages to proper MPS references. However, something is still strange: why is this textgen associated to a transformation concept, and not to a contractset (SyVOLT) concept? Is it because the contractset concept was not finished yet at the time?

**Comment by BentleyJOakes** [comment]
A toplevel script requires both the transformation rules and the contracts to be proved. Maybe the textgen should be in a different location?

**Comment by levilucio** [comment]
In any case we are doing things differently now. For the piping to work properly, we use an intention to write the files to the proper locations using normal java instead of textgen. The problem is also that we could not launch the textgen programmatically...

It is a good good question, whether a pointer from the transformation towards the contracts should exist, or the other way around. I'm thinking more in the direction of transformation towards contract, because the transformation should have contracts associated to it. In that case, I guess the toplevel should be created at the level of the DSLTrans transformation, although because we do it with the intention that does not really make a difference anymore...
