### ISSUE TITLE
pre-load type of attribute reference class type with the type of the Match or Apply Class 

### ISSUE THREAD

**Issue by levilucio** [mbeddr/language_verification#29]
- Create a Match or Apply class of some type in a DSLTrans rule.
- Inside the class, create an attribute. It is possible to select the type of the class as well as the attribute itself inside the reference.
- The type of the class for the attribute can be different than the one for the match or the apply class.
- The type of the class in the reference should be initialised with the type of the encompassing Match/Apply class.

**Comment by BentleyJOakes** [comment]
Fixed in commit ad06168206e381be296b4f8fcfad30373df335d5
