### ISSUE TITLE
MPS DSLTrans only runs endogenous transformations

### ISSUE THREAD

**Issue by levilucio** [mbeddr/language_verification#41]
- Two metamodels are loaded in the loadMetaModel in MPSModelLoader / DSLTransRunner plugin, from the input and output metamodels of the transformation.
- When a transformation is ran DSLTrans complains that two roots exist in the metamodel and does not run the transformation.
- The two roots are correct, and the exception should not be thrown. Endogenous transformations work.

**Comment by BentleyJOakes** [comment]
Fixed by commit ac60ed27911ea38a1f69c5b0f74e0fc7c2b868a2. Requires forked version of DSLTransEngine.
