### ISSUE TITLE
Matching fails for ineheritance in backward links

### ISSUE THREAD

**Issue by BentleyJOakes** [mbeddr/language_verification#43]
For example, in the Families2Persons transformation:
tworkersSolveRef rule
Match: 
Company - Parent - City

Apply:
TownHall - Person

Backward links:
Person to Parent
TownHall to City

This rule does not match on the test model. However, changing the type of the Person in the Apply to a Man does properly match.

The metamodel is correct, such that Man is a subclass of Person.

**Comment by clagms** [comment]
In the eclipse version, there is a property in the apply class "Person" that allows for matching for inheritance.
Is that property checked?
I think it is called "Allow inheritance".

**Comment by BentleyJOakes** [comment]
This also exists in the MPS version, as 'allow inheritance' on each class. Thanks, it works now.

And I'll change the DSLTrans transformation importer, so that this is set to default as true for each class when importing.
